---
title: "Heroin DOC Model"
author: "Patrick Hollowell"
date: "October 9, 2018"
output: html_document
---

```{r setup, include= FALSE}
knitr::opts_chunk$set(error = TRUE)
library(RCurl);library(readr); library(ggplot2); library(ggfortify); library(dplyr)
```

## Heroin Arrests Model

Loads up Heroin Analysis csv
Includes quarterly data from each county from Q1 2013 through the end of Q4 2017.
```{r, include=TRUE}
docCount.link <- "https://raw.githubusercontent.com/TeamDemacian/prevention-targeting/master/data/group4-doc/Heroin%20Incident%20Qty%20Arrest%20Analysis%20Data.csv"
read.succ.docCount <- getURI(docCount.link)
succ.docCount.dt <- read_csv(read.succ.docCount)
```

```{r}
View(succ.docCount.dt)
```

Assign Variables for Regression
```{r}
Incidents <- c(succ.docCount.dt$`Heroin Incidents`) #X1
Qty <- c(succ.docCount.dt$`Heroin Qty Seized (Kg)`) #X2
Arrests <- c(succ.docCount.dt$`Heroin Arrests`) #Y
```

Multiple Linear Regression.
Estimated Arrests= B0 + B1Qty + B2 Incidents + error
```{r}
 Regression <- lm( Arrests ~ Incidents + Qty)
summary(Regression) # show results
```

Other regression summaries 
```{r}
anova(Regression) # anova table 
vcov(Regression) # covariance matrix for model parameters 
```

Quick regression plots for analysis of the model
```{r}
autoplot((Regression), label.size = 3) 
```

